/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SalvaVelarte (https://sketchfab.com/SalvaVelarte)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nintendo-switch-19d52d793b8a47ef949c44e7879827e2
title: Nintendo Switch
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";

const Nintendo_Switch = (props) => {
  const group = useRef();
  const { nodes, materials } = props.nodesAndMaterial;

  // On load, filter all references of the meshes of the 3d Object,
  // and save it to the meshes_array hook in app.js
  // Allows app.js to directly manipulate the color of the meshes.
  useEffect(() => {
    var ObjtoArray = Object.values(materials);
    const meshes_array = ObjtoArray.filter(
      (obj) => obj.type === "MeshStandardMaterial"
    );
    props.handleSetMesh(meshes_array);
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.mesh_0.geometry}
          material={materials.aiStandardSurface3SG2}
        />
        <mesh
          geometry={nodes.mesh_1.geometry}
          material={materials.aiStandardSurface1SG}
        />
        <mesh
          geometry={nodes.mesh_2.geometry}
          material={materials.aiStandardSurface3SG}
        />
        <mesh
          geometry={nodes.mesh_3.geometry}
          material={materials.aiStandardSurface3SG1}
        />
        <mesh
          geometry={nodes.mesh_4.geometry}
          material={materials.aiStandardSurface4SG}
        />
        <mesh
          geometry={nodes.mesh_5.geometry}
          material={materials.aiStandardSurface5SG}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/switch.gltf");
export default Nintendo_Switch;
